### ISSUE TITLE
`ansible-galaxy collection install -r requirements.yml` might not be working as expected

### ISSUE THREAD

**Issue by mpressen** [guillaumebriday/kamal-ansible-manager#11]
On Ubuntu 24.04, I add to diverge from the README#getting-started.

![image](https://github.com/user-attachments/assets/0509fc9d-610e-4d41-b23f-961e5af5859b)

then 
![image](https://github.com/user-attachments/assets/4815b7ca-1fb0-4cd6-b5b6-c1e0a6308469)

I feell like requirements.yml is not working as expected.

**Comment by lwg21** [comment]
Getting the same error on macOS 14.6.1. Using `ansible-galaxy role install geerlingguy.swap` worked, thank you @mpressen.

**Comment by guillaumebriday** [comment]
Fixed by https://github.com/guillaumebriday/kamal-ansible-manager/pull/12
