### ISSUE TITLE
Integrate CrowdSec

### ISSUE THREAD

**Issue by cbldev** [guillaumebriday/kamal-ansible-manager#7]
What do you think of CrowdSec integration instead of fail2ban?

Official documentation: https://docs.crowdsec.net/u/getting_started/installation/linux

A note who can helps: https://notes.tontoncyber.fr/Num%C3%A9rique/Cybers%C3%A9curit%C3%A9+%F0%9F%94%90/CTI#CrowdSec

**Comment by guillaumebriday** [comment]
I wasn't familiar with Crowdsec, but it looks interesting! I don’t have any experience with it yet, and I imagine Fail2ban is more widely known, so people might feel more comfortable with that.

I'll give Crowdsec a try, though

thanks for the recommendation!
