### ISSUE TITLE
SSH PasswordAuthentication

### ISSUE THREAD

**Issue by aeuillot** [guillaumebriday/kamal-ansible-manager#9]
Hi @guillaumebriday,

Thanks for your work, it's very useful :)

On my new ubuntu distribution, I got surprised because this file `/etc/ssh/sshd_config.d/50-cloud-init.conf` is referenced in `/etc/ssh/sshd_config`, via the following line: `Include /etc/ssh/sshd_config.d/*.conf`

And unfortunately, this file contains: `PasswordAuthentication yes`, and overload the password configuration.

Do you think the ssh task should take into account this specific case ?

Regards

**Comment by guillaumebriday** [comment]
Hum, I also have the `Include /etc/ssh/sshd_config.d/*.conf` but in one of the default configuration file, the `PasswordAuthentication` is set to false by default, I think it's very specific to some images and it would be hard to find a good way to handle all cases, but I might be wrong?
